# Site settings
title: Daniel Andrade
description: "Personal website"
baseurl: ""
url: "https://dcandrade.com"

# User settings
username: Daniel Andrade
user_description: Computer Engineer undergraduate student @ UEFS
user_title: Daniel Andrade
email: dca650@gmail.com
twitter_username: ddcandrade
github_username:  dcandrade
gplus_username:  +DanielAndradeC
linkedin_public_url: dcandrade
disqus_username: dcandrade
profile_picture: ./assets/img/profile.jpg

# header nav Links
menu:
  #- title: posts
  #  url: /posts
  - title: publications
    url: /publications.html
  - title: talks
    url: /talks.html
  - title: lattes
    url: http://lattes.cnpq.br/5346136314135481
  - title: about me
    url: /about

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false


# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    #- title: my posts
    #  url: /posts
    #  key_trigger: 2
    #- title: series
    #  url: /series
    #  key_trigger: 3
    #- title: tags
    #  url: /tags
    #  key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5

  section_2:
        - title: publications
          url: /publications.html
          key_trigger: 1
        - title: talks
          url: /talks.html
          key_trigger: 2

  section_3:
    - title: github
      url: http://www.github.com/dcandrade
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/ddcandrade
      new_tab: true
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: Machine Learning A-Z
    url: https://github.com/dcandrade/machine-learning-a-z
  - name: Digital Signal Processing
    url: https://github.com/dcandrade/digital-signal-processing
  - name: Payfast
    url: https://github.com/dcandrade/payfast

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
